- name: Check that the somefile.conf exists
  stat:
    path: /etc/test.txt
  register: stat_result

- name: Create the file, if it doesnt exist already
  debug:
    msg: "File is not present"
  when: stat_result.stat.exists == False 