- name: Check that the somefile.conf exists
  stat:
    path: /etc/test
  register: stat_result

- name: Status of file
  debug:
    msg: "File is not present"
  when: stat_result.stat.exists == False 